- name: Generate history index (safe HTML with absolute Back link)
        shell: bash
        run: |
          set -euo pipefail

          # Detect your site output directory
          if [ -d "site_out" ]; then SITE_DIR="site_out"; else SITE_DIR="_site"; fi
          HIST_DIR="${SITE_DIR}/report_history"

          # Build link list
          mapfile -t FILES < <(find "$HIST_DIR" -maxdepth 1 -type f -name 'firmware_analysis_report_*.html' | sort -r)
          LINKS=""
          for f in "${FILES[@]}"; do
            b="$(basename "$f")"
            label="$(echo "$b" \
              | sed -E 's/^firmware_analysis_report_([0-9]{8})_([0-9]{6})(_[0-9]+)?_(.*)\.html$/Date: \1 Time: \2 Build: \3 OS: \4/' \
              | sed 's/_//g' \
              | sed 's/Build:  /Build: NA /')"
            LINKS="${LINKS}<li><a href=\"${b}\">${label}</a></li>"
          done

          # Write a full HTML file using a SINGLE-QUOTED heredoc
          cat > "${HIST_DIR}/index.html" <<'HTML'
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Report History</title>
  <style>
    body { font-family: system-ui, -apple-system, Segoe UI, Roboto, sans-serif; margin: 2rem; color: #111827; }
    a { color: #1d4ed8; text-decoration: none; }
    a:hover { text-decoration: underline; }
    .back { margin-bottom: 1rem; display: inline-block; }
    h1 { margin: .2rem 0 1rem; }
    ul { padding-left: 1.2rem; }
    li { margin: .35rem 0; }
    .note { margin-top: 1.5rem; color: #6b7280; font-size: .9rem; }
  </style>
</head>
<body>
  /firmware_monitor/← Back to Latest Report</a>
  <h1>Archived Report History</h1>
  <ul>
HTML

          # Append the dynamic links safely
          printf '%s\n' "${LINKS}" >> "${HIST_DIR}/index.html"

          # Close out the HTML
          cat >> "${HIST_DIR}/index.html" <<'HTML'
  </ul>
  <div class="note">All reports are archived here: /firmware_monitor/report_history/</div>
</body>
</html>
HTML

          # Ensure static hosting
          touch "${SITE_DIR}/.nojekyll"

          echo "== Sanity check =="
          echo "Expect an <a ...> anchor on the first line after </style>:"
          sed -n '1,60p' "${HIST_DIR}/index.html" | sed -n '15,30p'  # quick window around the anchor