name: Firmware Monitor CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allow manual triggering

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    
    # CRITICAL: Define permissions for GitHub Pages deployment (Correctly nested under job)
    permissions:
      contents: read
      pages: write 
      id-token: write 

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Run Analysis Script and generate reports
      # Passes the GitHub Run Number to the Python script
      run: python firmware_monitor.py --build-number ${{ github.run_number }}
      
    - name: Prepare Report History Directory for Pages
      # Moves all generated reports from 'reports/' into 'report_history/'
      run: |
        mkdir -p report_history
        mv reports/* report_history/

    - name: Setup Pages
      # Configures the Pages environment
      uses: actions/configure-pages@v5

    - name: Upload Report Artifacts
      # Uploads the 'report_history' folder content as the deployment artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'report_history/' 

    - name: Deploy to GitHub Pages
      id: deployment
      # Deploys the uploaded artifact to the 'gh-pages' branch
      uses: actions/deploy-pages@v4
      
    # ---------------------------------------------
    # Docker steps (retained from previous configuration)
    # ---------------------------------------------

    - name: Log in to GitHub Container Registry (GHCR)
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:latest
          ghcr.io/${{ github.repository }}:${{ github.sha }}
